---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile
  - Gemfile.lock
  - "**.rb"
exclude_paths:
- features/
- spec/
