#!/usr/bin/env ruby
# frozen_string_literal: true

lib = File.expand_path("../../lib", __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require "bundler/setup"
require "piawe"

ruleset = Piawe::Reader::Ruleset.new.read "rules.json"
reporter = Piawe::Reporter::Csv.new current_date: Date.today,
                                    ruleset: ruleset
puts reporter.generate Piawe::Reader::People.new.read "people.json"
